package worldstate

var WorldStateLocations = map[string]string{
	"SolNode0":         "SolNode0",
	"SolNode1":         "Galatea (Neptune)",
	"SolNode2":         "Aphrodite (Venus)",
	"SolNode3":         "Cordelia (Uranus)",
	"SolNode4":         "Acheron (Pluto)",
	"SolNode5":         "Perdita (Uranus)",
	"SolNode6":         "Despina (Neptune)",
	"SolNode7":         "Epimetheus (Saturn)",
	"SolNode8":         "Nix (Pluto)",
	"SolNode9":         "Rosalind (Uranus)",
	"SolNode10":        "Thebe (Jupiter)",
	"SolNode11":        "Tharsis (Mars)",
	"SolNode12":        "Elion (Mercury)",
	"SolNode13":        "Bianca (Uranus)",
	"SolNode14":        "Ultor (Mars)",
	"SolNode15":        "Pacific (Earth)",
	"SolNode16":        "Augustus (Mars)",
	"SolNode17":        "Proteus (Neptune)",
	"SolNode18":        "Rhea (Saturn)",
	"SolNode19":        "Enceladus (Saturn)",
	"SolNode20":        "Telesto (Saturn)",
	"SolNode21":        "Narcissus (Pluto)",
	"SolNode22":        "Tessera (Venus)",
	"SolNode23":        "Cytherean (Venus)",
	"SolNode24":        "Oro (Earth)",
	"SolNode25":        "Callisto (Jupiter)",
	"SolNode26":        "Lith (Earth)",
	"SolNode27":        "E Prime (Earth)",
	"SolNode28":        "M Prime (Mercury)",
	"SolNode29":        "Oberon (Uranus)",
	"SolNode30":        "Olympus (Mars)",
	"SolNode31":        "Anthe (Saturn)",
	"SolNode32":        "Tethys (Saturn)",
	"SolNode33":        "Ariel (Uranus)",
	"SolNode34":        "Sycorax (Uranus)",
	"SolNode35":        "Arcadia (Mars)",
	"SolNode36":        "Martialis (Mars)",
	"SolNode37":        "Pallene (Saturn)",
	"SolNode38":        "Minthe (Pluto)",
	"SolNode39":        "Everest (Earth)",
	"SolNode40":        "Prospero (Uranus)",
	"SolNode41":        "Arval (Mars)",
	"SolNode42":        "Helene (Saturn)",
	"SolNode43":        "Cerberus (Pluto)",
	"SolNode44":        "Mimas (Saturn)",
	"SolNode45":        "Ara (Mars)",
	"SolNode46":        "Spear (Mars)",
	"SolNode47":        "Janus (Saturn)",
	"SolNode48":        "Regna (Pluto)",
	"SolNode49":        "Larissa (Neptune)",
	"SolNode50":        "Numa (Saturn)",
	"SolNode51":        "Hades (Pluto)",
	"SolNode52":        "Portia (Uranus)",
	"SolNode53":        "Themisto (Jupiter)",
	"SolNode54":        "Silvanus (Mars)",
	"SolNode55":        "Methone (Saturn)",
	"SolNode56":        "Cypress (Pluto)",
	"SolNode57":        "Sao (Neptune)",
	"SolNode58":        "Hellas (Mars)",
	"SolNode59":        "Eurasia (Earth)",
	"SolNode60":        "Caliban (Uranus)",
	"SolNode61":        "Ishtar (Venus)",
	"SolNode62":        "Neso (Neptune)",
	"SolNode63":        "Mantle (Earth)",
	"SolNode64":        "Umbriel (Uranus)",
	"SolNode65":        "Gradivus (Mars)",
	"SolNode66":        "Unda (Venus)",
	"SolNode67":        "Dione (Saturn)",
	"SolNode68":        "Vallis (Mars)",
	"SolNode69":        "Ophelia (Uranus)",
	"SolNode70":        "Cassini (Saturn)",
	"SolNode71":        "Vesper (Venus)",
	"SolNode72":        "Outer Terminus (Pluto)",
	"SolNode73":        "Ananke (Jupiter)",
	"SolNode74":        "Carme (Jupiter)",
	"SolNode75":        "Cervantes (Earth)",
	"SolNode76":        "Hydra (Pluto)",
	"SolNode77":        "Cupid (Uranus)",
	"SolNode78":        "Triton (Neptune)",
	"SolNode79":        "Cambria (Earth)",
	"SolNode80":        "Phoebe (Saturn)",
	"SolNode81":        "Palus (Pluto)",
	"SolNode82":        "Calypso (Saturn)",
	"SolNode83":        "Cressida (Uranus)",
	"SolNode84":        "Nereid (Neptune)",
	"SolNode85":        "Gaia (Earth)",
	"SolNode86":        "Aegaeon (Saturn)",
	"SolNode87":        "Ganymede (Jupiter)",
	"SolNode88":        "Adrastea (Jupiter)",
	"SolNode89":        "Mariana (Earth)",
	"SolNode90":        "Miranda",
	"SolNode91":        "Iapetus (Saturn)",
	"SolNode92":        "Charon (Pluto)",
	"SolNode93":        "Keeler (Saturn)",
	"SolNode94":        "Apollodorus (Mercury)",
	"SolNode95":        "Thalassa (Neptune)",
	"SolNode96":        "Titan (Saturn)",
	"SolNode97":        "Amalthea (Jupiter)",
	"SolNode98":        "Desdemona (Uranus)",
	"SolNode99":        "War (Mars)",
	"SolNode100":       "Elara (Jupiter)",
	"SolNode101":       "Kiliken (Venus)",
	"SolNode102":       "Oceanum (Pluto)",
	"SolNode103":       "Terminus (Mercury)",
	"SolNode104":       "Fossa (Venus)",
	"SolNode105":       "Titania (Uranus)",
	"SolNode106":       "Alator (Mars)",
	"SolNode107":       "Venera (Venus)",
	"SolNode108":       "Tolstoj (Mercury)",
	"SolNode109":       "Linea (Venus)",
	"SolNode110":       "Hyperion (Saturn)",
	"SolNode111":       "Juliet (Uranus)",
	"SolNode112":       "Setebos (Uranus)",
	"SolNode113":       "Ares (Mars)",
	"SolNode114":       "Puck (Uranus)",
	"SolNode115":       "Quirinus (Mars)",
	"SolNode116":       "Mab (Uranus)",
	"SolNode117":       "Naiad (Neptune)",
	"SolNode118":       "Laomedeia (Neptune)",
	"SolNode119":       "Caloris (Mercury)",
	"SolNode120":       "Halimede (Neptune)",
	"SolNode121":       "Carpo (Jupiter)",
	"SolNode122":       "Stephano (Uranus)",
	"SolNode123":       "V Prime (Venus)",
	"SolNode124":       "Trinculo (Uranus)",
	"SolNode125":       "Io (Jupiter)",
	"SolNode126":       "Metis (Jupiter)",
	"SolNode127":       "Psamathe (Neptune)",
	"SolNode128":       "E Gate (Venus)",
	"SolNode129":       "SolNode129",
	"SolNode130":       "Lares (Mercury)",
	"SolNode131":       "Pallas (Ceres)",
	"SolNode132":       "Bode (Ceres)",
	"SolNode133":       "Vedic (Ceres)",
	"SolNode134":       "Varro (Ceres)",
	"SolNode135":       "Thon (Ceres)",
	"SolNode136":       "Olla (Ceres)",
	"SolNode137":       "Nuovo (Ceres)",
	"SolNode138":       "Ludi (Ceres)",
	"SolNode139":       "Lex (Ceres)",
	"SolNode140":       "Kiste (Ceres)",
	"SolNode141":       "Ker (Ceres)",
	"SolNode142":       "Hapke (Ceres)",
	"SolNode143":       "Gefion (Ceres)",
	"SolNode144":       "Exta (Ceres)",
	"SolNode145":       "Egeria (Ceres)",
	"SolNode146":       "Draco (Ceres)",
	"SolNode147":       "Cinxia (Ceres)",
	"SolNode148":       "Cerium (Ceres)",
	"SolNode149":       "Casta (Ceres)",
	"SolNode150":       "Albedo (Ceres)",
	"SolNode151":       "Acanth (Eris)",
	"SolNode152":       "Ascar (Eris)",
	"SolNode153":       "Brugia (Eris)",
	"SolNode154":       "Candiru (Eris)",
	"SolNode155":       "Cosis (Eris)",
	"SolNode156":       "Cyath (Eris)",
	"SolNode157":       "Giardia (Eris)",
	"SolNode158":       "Gnathos (Eris)",
	"SolNode159":       "Lepis (Eris)",
	"SolNode160":       "Histo (Eris)",
	"SolNode161":       "Hymeno (Eris)",
	"SolNode162":       "Isos (Eris)",
	"SolNode163":       "Ixodes (Eris)",
	"SolNode164":       "Kala-azar (Eris)",
	"SolNode165":       "Sporid (Eris)",
	"SolNode166":       "Nimus (Eris)",
	"SolNode167":       "Oestrus (Eris)",
	"SolNode168":       "Phalan (Eris)",
	"SolNode169":       "Psoro (Eris)",
	"SolNode170":       "Ranova (Eris)",
	"SolNode171":       "Saxis (Eris)",
	"SolNode172":       "Xini (Eris)",
	"SolNode173":       "Solium (Eris)",
	"SolNode174":       "Sparga (Eris)",
	"SolNode175":       "Naeglar (Eris)",
	"SolNode176":       "Viver (Eris)",
	"SolNode177":       "Kappa (Sedna)",
	"SolNode178":       "Hyosube (Sedna)",
	"SolNode179":       "Jengu (Sedna)",
	"SolNode180":       "Undine (Sedna)",
	"SolNode181":       "Adaro (Sedna)",
	"SolNode182":       "Camenae (Sedna)",
	"SolNode183":       "Vodyanoi (Sedna)",
	"SolNode184":       "Rusalka (Sedna)",
	"SolNode185":       "Berehynia (Sedna)",
	"SolNode186":       "Phithale (Sedna)",
	"SolNode187":       "Selkie (Sedna)",
	"SolNode188":       "Kelpie (Sedna)",
	"SolNode189":       "Naga (Sedna)",
	"SolNode190":       "Nakki (Sedna)",
	"SolNode191":       "Marid (Sedna)",
	"SolNode192":       "Tikoloshe (Sedna)",
	"SolNode193":       "Merrow (Sedna)",
	"SolNode194":       "Ponaturi (Sedna)",
	"SolNode195":       "Hydron (Sedna)",
	"SolNode196":       "Charybdis (Sedna)",
	"SolNode197":       "Graeae (Sedna)",
	"SolNode198":       "Scylla (Sedna)",
	"SolNode199":       "Yam (Sedna)",
	"SolNode200":       "Veles (Sedna)",
	"SolNode201":       "Tiamat (Sedna)",
	"SolNode202":       "Yemaja (Sedna)",
	"SolNode203":       "Abaddon (Europa)",
	"SolNode204":       "Armaros (Europa)",
	"SolNode205":       "Baal (Europa)",
	"SolNode206":       "Eligor (Europa)",
	"SolNode207":       "Gamygyn (Europa)",
	"SolNode208":       "Lillith (Europa)",
	"SolNode209":       "Morax (Europa)",
	"SolNode210":       "Naamah (Europa)",
	"SolNode211":       "Ose (Europa)",
	"SolNode212":       "Paimon (Europa)",
	"SolNode213":       "Shax (Europa)",
	"SolNode214":       "Sorath (Europa)",
	"SolNode215":       "Valac (Europa)",
	"SolNode216":       "Valefor (Europa)",
	"SolNode217":       "Orias (Europa)",
	"SolNode218":       "Zagan (Europa)",
	"SolNode219":       "Beleth (Europa)",
	"SolNode220":       "Kokabiel (Europa)",
	"SolNode221":       "Neruda (Mercury)",
	"SolNode222":       "Eminescu (Mercury)",
	"SolNode223":       "Boethius (Mercury)",
	"SolNode224":       "Odin (Mercury)",
	"SolNode225":       "Suisei (Mercury)",
	"SolNode226":       "Pantheon (Mercury)",
	"SolNode227":       "Verdi (Mercury)",
	"SolNode300":       "Plato (Lua)",
	"SolNode301":       "Grimaldi (Lua)",
	"SolNode302":       "Tycho (Lua)",
	"SolNode304":       "Copernicus (Lua)",
	"SolNode305":       "Stöfler (Lua)",
	"SolNode306":       "Pavlov (Lua)",
	"SolNode307":       "Zeipel (Lua)",
	"SolNode400":       "Teshub (Void)",
	"SolNode401":       "Hepit (Void)",
	"SolNode402":       "Taranis (Void)",
	"SolNode403":       "Tiwaz (Void)",
	"SolNode404":       "Striborg (Void)",
	"SolNode405":       "Ani (Void)",
	"SolNode406":       "Ukko (Void)",
	"SolNode407":       "Oxomoco (Void)",
	"SolNode408":       "Belenus (Void)",
	"SolNode409":       "Mot (Void)",
	"SolNode410":       "Aten (Void)",
	"SolNode411":       "SolNode411 (Void)",
	"SolNode412":       "Mithra (Void)",
	"SolNode413":       "SolNode413 (Void)",
	"SolNode741":       "Koro (Kuva Fortress)",
	"SolNode742":       "Nabuk (Kuva Fortress)",
	"SolNode743":       "Rotuma (Kuva Fortress)",
	"SolNode744":       "Taveuni (Kuva Fortress)",
	"SolNode745":       "Tamu (Kuva Fortress)",
	"SolNode746":       "Dakata (Kuva Fortress)",
	"SolNode747":       "Pago (Kuva Fortress)",
	"SolNode748":       "Garus (Kuva Fortress)",
	"SolNode901":       "Caduceus",
	"SolNode902":       "Montes (Venus)",
	"SolNode903":       "Erpo (Earth)",
	"SolNode904":       "Syrtis (Mars)",
	"SolNode905":       "Galilea (Jupiter)",
	"SolNode906":       "Pandora (Saturn)",
	"SolNode907":       "Caelus (Uranus)",
	"SolNode908":       "Salacia (Neptune)",
	"SettlementNode1":  "Roche (Phobos)",
	"SettlementNode2":  "Skyresh (Phobos)",
	"SettlementNode3":  "Stickney (Phobos)",
	"SettlementNode4":  "Drunlo (Phobos)",
	"SettlementNode5":  "Grildrig (Phobos)",
	"SettlementNode6":  "Limtoc (Phobos)",
	"SettlementNode7":  "Hall (Phobos)",
	"SettlementNode8":  "Reldresal (Phobos)",
	"SettlementNode9":  "Clustril (Phobos)",
	"SettlementNode10": "Kepler (Phobos)",
	"SettlementNode11": "Gulliver (Phobos)",
	"SettlementNode12": "Monolith (Phobos)",
	"SettlementNode13": "D'Arrest (Phobos)",
	"SettlementNode14": "Shklovsky (Phobos)",
	"SettlementNode15": "Sharpless (Phobos)",
	"SettlementNode16": "Wendell (Phobos)",
	"SettlementNode17": "Flimnap (Phobos)",
	"SettlementNode18": "Opik (Phobos)",
	"SettlementNode19": "Todd (Phobos)",
	"SettlementNode20": "Iliad (Phobos)",
	"MercuryHUB":       "Larunda Relay (Mercury)",
	"VenusHUB":         "Vesper Relay (Venus)",
	"EarthHUB":         "Strata Relay (Earth)",
	"SaturnHUB":        "Kronia Relay (Saturn)",
	"ErisHUB":          "Kuiper Relay (Eris)",
	"EuropaHUB":        "Leonov Relay (Europa)",
	"PlutoHUB":         "Orcus Relay (Pluto)",
	"EventNode0":       "Balor",
	"EventNode1":       "Tethra",
	"EventNode2":       "Operation Gate Crash",
	"EventNode3":       "Elatha",
	"EventNode4":       "Bres",
	"EventNode5":       "Birog",
	"EventNode6":       "Tyl Reygor Seal Lab",
	"EventNode7":       "Buarainech",
	"EventNode8":       "Corb",
	"EventNode9":       "Operation Gate Crash Pt. 2",
	"EventNode10":      "Lugh",
	"EventNode11":      "Nemed",
	"EventNode12":      "Operation Cryotic Front",
	"EventNode13":      "Shifting Sands",
	"EventNode14":      "Gate Crash",
	"EventNode15":      "Operation Cryotic Front",
	"EventNode16":      "Operation Cryotic Front",
	"EventNode17":      "Operation Cryotic Front",
	"EventNode18":      "Operation Blackout Pt. 1",
	"EventNode19":      "Operation Blackout Pt. 1",
	"EventNode20":      "Tyl Regor Sea Lab",
	"EventNode22":      "Tyl Regor Sea Lab",
	"EventNode761":     "The Index",
	"EventNode762":     "The Index pt 2",
	"EventNode763":     "The Index Endurance",
	"PvpNode0":         "Conclave Capture the Cephalon",
	"PvpNode1":         "Conclave",
	"PvpNode2":         "Conclave",
	"PvpNode3":         "Conclave Capture the Cephalon",
	"PvpNode4":         "Conclave",
	"PvpNode5":         "Conclave",
	"PvpNode6":         "Conclave",
	"PvpNode7":         "Conclave",
	"PvpNode8":         "Conclave",
	"PvpNode9":         "Conclave Team Domination",
	"PvpNode10":        "Conclave Domination",
	"PvpNode11":        "Conclave Domination",
	"PvpNode12":        "Conclave Domination",
	"PvpNode13":        "Tactical Alert: Snoball Fight!",
	"PvpNode14":        "Conclave: Quick Steel",
	"ClanNode0":        "Romula (Venus)",
	"ClanNode1":        "Malva (Venus)",
	"ClanNode2":        "Coba (Earth)",
	"ClanNode3":        "Tikal (Earth)",
	"ClanNode4":        "Sinai (Jupiter)",
	"ClanNode5":        "Cameria (Jupiter)",
	"ClanNode6":        "Larzac (Europa)",
	"ClanNode7":        "Cholistan (Europa)",
	"ClanNode8":        "Kadesh (Mars)",
	"ClanNode9":        "Wahiba (Mars)",
	"ClanNode10":       "Memphis (Phobos)",
	"ClanNode11":       "Zeugma (Phobos)",
	"ClanNode12":       "Caracol (Saturn)",
	"ClanNode13":       "Piscinas (Saturn)",
	"ClanNode14":       "Amarna (Sedna)",
	"ClanNode15":       "Sangeru (Sedna)",
	"ClanNode16":       "Ur (Uranus)",
	"ClanNode17":       "Assur (Uranus)",
	"ClanNode18":       "Akkad (Eris)",
	"ClanNode19":       "Zabala (Eris)",
	"ClanNode20":       "Yursa (Neptune)",
	"ClanNode21":       "Kelashin (Neptune)",
	"ClanNode22":       "Seimeni (Ceres)",
	"ClanNode23":       "Gabii (Ceres)",
	"ClanNode24":       "Sechura (Pluto)",
	"ClanNode25":       "Hieracon (Pluto)",

	"/Lotus/Types/Keys/SortieBossKeyPhorid": "Sortie Boss: Phorid",
}

var WorldStateMissionTypes = map[string]string{
	"MT_EXCAVATE":       "Excavation",
	"MT_SABOTAGE":       "Sabotage",
	"MT_MOBILE_DEFENSE": "Mobile Defense",
	"MT_ASSASSINATION":  "Assassination",
	"MT_EXTERMINATION":  "Extermination",
	"MT_HIVE":           "Hive",
	"MT_DEFENSE":        "Defense",
	"MT_TERRITORY":      "Interception",
	"MT_ARENA":          "Rathuum",
	"MT_PVP":            "Conclave",
	"MT_RESCUE":         "Rescue",
	"MT_INTEL":          "Spy",
	"MT_SURVIVAL":       "Survival",
	"MT_CAPTURE":        "Capture",
	"MT_SECTOR":         "Dark Sector",
	"MT_RETRIEVAL":      "Hijack",
	"MT_ASSAULT":        "Assault",
	"MT_EVACUATION":     "Evacuation",
}

var WorldStateFaction = map[string]string{
	"FC_GRINEER":     "Grineer",
	"FC_CORPUS":      "Corpus",
	"FC_INFESTATION": "Infested",
	"FC_CORRUPTED":   "Corrupted",
	"FC_OROKIN":      "Orokin",
}

var WorldStateItems = map[string]string{
	"/Lotus/StoreItems/Types/Recipes/Components/OrokinCatalystBlueprint": "Orokin Catalyst Blueprint",
	"/Lotus/StoreItems/Types/Recipes/Components/OrokinReactorBlueprint":  "Orokin Reactor Blueprint",
}
